version: '3.8'

services:
  client:
    build:
      context: ./client
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_INTERNAL_API_URL=http://backend:4000
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

  backend:
    build:
      context: ./backend-nodejs
    ports:
      - "4000:4000"
    depends_on:
      - clip-service
    environment:
      - CLIP_SERVICE_URL=http://clip-service:5000
      - MONGO_URI=mongodb+srv://nguyendinhtu11022002:v0YGqRqtzoUw72Mp@inbe.htme7st.mongodb.net/
      - NODE_ENV=development
    volumes:
      - ./backend-nodejs:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    command: npm start

  clip-service:
    build:
      context: ./clip-python
    ports:
      - "5000:5000"
    volumes:
      - ./clip-python:/app
      - clip-storage:/app/image_storage
      - clip-data:/app/data
      - clip-model-cache:/root/.cache/clip
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    # command: flask run --host=0.0.0.0 --port=5000 --reload

networks:
  app-network:
    driver: bridge

volumes:
  backend-uploads:
  clip-storage:
  clip-data:
  clip-model-cache:
  mongo-data:
